### ISSUE TITLE
jasmine is not defined

### ISSUE THREAD

**Issue by hlassiege** [sindresorhus/gulp-jasmine#38]
Hi,
I'm trying to use a Jasmine reporter.

The intial build was : 

```
// Include gulp
var gulp = require('gulp');
var jasmine = require('gulp-jasmine');

gulp.task('specs', function () {
    return gulp.src('src/spec/*.js')
        .pipe(jasmine();
});
```

It works correctly.

To add a reporter, I just add a require at the top of the gulpfile.js. And this operation fails :
```
var jasmine = require('gulp-jasmine');
var reporters = require('jasmine-reporters');
```
Result :
```
gulp build
ReferenceError: jasmine is not defined
    at C:\***\node_modules\jasmine-reporters\src\jasmine.console_reporter.js:2:11
    at Object.<anonymous> (C:\***\node_modules\jasmine-reporters\src\jasmine.console_reporter.js:144:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\***node_modules\jasmine-reporters\src\load_reporters.js:1:63)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

    at Object.<anonymous> (C:\***\gulpfile.js:18:17)
```

Any idea ?

**Comment by jbblanchet** [comment]
You must have installed jasmine-reporters 1.0.1. Their NPM is out of order, and 1.0.1 came out after 2.0.3, which is the latest version with support for jasmine 2.0+.

Closing for now, please feel free to reopen if it didn't solve your problem.
